namespace Terminal.Gui.Xaml.Generation;

/// <summary>
/// Provides code generation templates for XAML code generation.
/// </summary>
public static class CodeTemplates
{
        /// <summary>
        /// Default template for generated classes.
        /// </summary>
    public const string DefaultClassTemplate = @"// <auto-generated/>
namespace {NAMESPACE} {{
    /// <summary>Generated from XAML</summary>
    public partial class {CLASSNAME} {{
        public void InitializeComponent() {{ /* XAML parsing logic */ }}
        // TODO: Add fields for named elements
        // TODO: Add event handler stubs
    }}
}}";

    // Add more templates as needed
}
