using System;
using System.IO;
using System.Linq;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

// Small Roslyn-based out-of-process build helper for Terminal.Gui.Xaml.
// Parses very small, simple XAML (XML) fragments and emits C# code that constructs
// Terminal.Gui controls. This is an example generator to demonstrate the pipeline
// and should be extended with full XAML semantics later.
namespace Terminal.Gui.Xaml.Build
{
    internal class Program
    {
        // Usage: Terminal.Gui.Xaml.Build.exe <projectDir> <outputDir>
        static int Main(string[] args)
        {
            if (args.Length < 2)
            {
                Console.Error.WriteLine("Terminal.Gui.Xaml.Build: missing required arguments. Usage: Terminal.Gui.Xaml.Build <projectDir> <outputDir>");
                return 1;
            }

            var projectDir = args[0];
            var outputDir = args[1];

            try
            {
                Directory.CreateDirectory(outputDir);

                var xamlFiles = Directory.GetFiles(projectDir, "*.xaml", SearchOption.AllDirectories);
                if (xamlFiles.Length == 0)
                {
                    // marker so MSBuild sees output
                    var marker = Path.Combine(outputDir, "__no_xaml.txt");
                    File.WriteAllText(marker, "No XAML files found. Placeholder created.");
                    Console.WriteLine(marker);
                    return 0;
                }

                foreach (var xamlPath in xamlFiles)
                {
                    var doc = XDocument.Load(xamlPath);
                    var root = doc.Root;
                    if (root == null)
                    {
                        Console.Error.WriteLine($"Skipping empty XAML: {xamlPath}");
                        continue;
                    }

                    var fileBase = Path.GetFileNameWithoutExtension(xamlPath);
                    var generatedFile = Path.Combine(outputDir, fileBase + ".g.cs");

                    var cu = GenerateCompilationUnit(root, fileBase);
                    var code = cu.NormalizeWhitespace().ToFullString();
                    File.WriteAllText(generatedFile, "// <auto-generated />\n" + code);
                    Console.WriteLine($"Generated {generatedFile} from {xamlPath}");
                }

                return 0;
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine("Terminal.Gui.Xaml.Build failed: " + ex);
                return 2;
            }
        }

        // Very small generator: creates a static class with a Create() method that returns a Terminal.Gui.View
        // and adds simple children (Label, Button, TextField) using their string/text constructors when available.
        private static CompilationUnitSyntax GenerateCompilationUnit(XElement root, string baseName)
        {
            // using directives
            var usings = new[]
            {
                UsingDirective(ParseName("System")),
            };

            // namespace: Terminal.Gui.Xaml.Generated
            var ns = NamespaceDeclaration(ParseName("Terminal.Gui.Xaml.Generated"))
                .WithMembers(SingletonList<MemberDeclarationSyntax>(
                    // public static class <BaseName>_Generated
                    ClassDeclaration(baseName + "_Generated")
                        .AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword))
                        .WithMembers(SingletonList<MemberDeclarationSyntax>(GenerateCreateMethod(root)))
                ));

            return CompilationUnit()
                .WithUsings(List(usings))
                .WithMembers(SingletonList<MemberDeclarationSyntax>(ns));
        }

        private static MethodDeclarationSyntax GenerateCreateMethod(XElement root)
        {
            // public static View Create()
            var returnType = ParseTypeName("Terminal.Gui.ViewBase.View");

            var statements = new System.Collections.Generic.List<StatementSyntax>();

            // var root = new Terminal.Gui.ViewBase.View();
            statements.Add(LocalDeclarationStatement(
                VariableDeclaration(ParseTypeName("var"))
                .WithVariables(SingletonSeparatedList(
                    VariableDeclarator("root")
                    .WithInitializer(
                        EqualsValueClause(ObjectCreationExpression(ParseTypeName("Terminal.Gui.ViewBase.View")).WithArgumentList(ArgumentList())))))));

            int counter = 1;
            foreach (var child in root.Elements())
            {
                var childVar = (child.Name.LocalName.ToLower() + counter).Replace("-", "_");
                counter++;

                // Simplified mapping: Label, Button, TextField -> constructors taking Text.
                var typeName = MapElementToType(child.Name.LocalName);

                ExpressionSyntax creationExpr;
                var textAttr = child.Attribute("Text")?.Value ?? child.Attribute("Content")?.Value ?? child.Value;
                // Create instance with parameterless ctor, then set Text property if textAttr is provided
                creationExpr = ObjectCreationExpression(ParseTypeName(typeName)).WithArgumentList(ArgumentList());

                // var childVar = new Type();
                statements.Add(LocalDeclarationStatement(
                    VariableDeclaration(ParseTypeName("var"))
                    .WithVariables(SingletonSeparatedList(
                        VariableDeclarator(childVar)
                        .WithInitializer(EqualsValueClause(creationExpr))))));

                if (!string.IsNullOrWhiteSpace(textAttr))
                {
                    // childVar.Text = "...";
                    statements.Add(ExpressionStatement(
                        AssignmentExpression(SyntaxKind.SimpleAssignmentExpression,
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, IdentifierName(childVar), IdentifierName("Text")),
                            LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(textAttr)))));
                }

                // root.Add(childVar);
                statements.Add(ExpressionStatement(
                    InvocationExpression(MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, IdentifierName("root"), IdentifierName("Add")))
                    .WithArgumentList(ArgumentList(SingletonSeparatedList(Argument(IdentifierName(childVar)))))));
            }

            // return root;
            statements.Add(ReturnStatement(IdentifierName("root")));

            var method = MethodDeclaration(returnType, "Create")
                .AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword))
                .WithBody(Block(statements));

            return method;
        }

        private static string MapElementToType(string elementName)
        {
            // Very small mapping; expand as needed. Assume Terminal.Gui types are in Terminal.Gui namespace.
            switch (elementName)
            {
                case "Label":
                case "TextBlock":
                    return "Terminal.Gui.Views.Label";
                case "Button":
                    return "Terminal.Gui.Views.Button";
                case "TextField":
                case "TextBox":
                    return "Terminal.Gui.Views.TextField";
                case "View":
                case "Panel":
                case "Window":
                default:
                    return "Terminal.Gui.ViewBase.View";
            }
        }
    }
}
