<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Disable documentation generation tasks inside sample builds -->
    <EnableXamlDocumentation>false</EnableXamlDocumentation>
    <SkipDocumentationTasks>true</SkipDocumentationTasks>
  </PropertyGroup>
</Project>
